In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

#state names dictionary from GitHub
us_state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'District of Columbia': 'DC',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Northern Mariana Islands':'MP',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Palau': 'PW',
    'Pennsylvania': 'PA',
    'Puerto Rico': 'PR',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virgin Islands': 'VI',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY',
}

In [2]:
#read data
mri = pd.read_csv("healthcare_q4.csv")
population = pd.read_excel("Population By State US Census Bureau.xlsx")
#convert state name to abbreviation
population['Provider License Number State Code_1'] = population['Geography'].map(us_state_abbrev)

In [3]:
#count number of MRI in each state
mri_count = mri.groupby("Provider License Number State Code_1").count()
mri_count = pd.merge(mri_count, population, on='Provider License Number State Code_1', how='left')
#calculate density
mri_density = pd.concat([
    mri_count['Provider License Number State Code_1'], 
    mri_count['Entity Type Code']*1000000/mri_count['Estimate; Total']
    ], axis=1)
mri_density = mri_density.rename(columns={0: "density"})
mri_density

   Provider License Number State Code_1   density
0                                    AK  1.353977
1                                    AR  1.343209
2                                    AZ  0.587376
3                                    CA  0.795222
4                                    CO  0.551824
5                                    CT  0.278205
6                                    DE  4.238491
7                                    FL  5.671046
8                                    GA  0.392094
9                                    GU       NaN
10                                   HI  0.703404
11                                   IA  0.320708
12                                   ID  0.603364
13                                   IL  1.244698
14                                   IN  0.453555
15                                   KS  0.688748
16                                   KY  0.678062
17                                   LA  1.286598
18                                   MA  2.209353
19                                   MD  2.668410
20                                   ME  2.255371
21                                   MI  1.511249
22                                   MN  1.821253
23                                   MO  0.658404
24                                   MS  0.334872
25                                   MT  1.942008
26                                   NC  0.497386
27                                   NJ  4.687416
28                                   NV  0.346293
29                                   NY  0.808153
30                                   OH  1.808824
31                                   OK  2.566570
32                                   OR  0.496879
33                                   PA  0.390915
34                                   PR  5.188871
35                                   RI  1.893692
36                                   SC  0.408710
37                                   TN  0.757876
38                                   TX  1.458810
39                                   UT  0.668016
40                                   WA  0.976295
41                                   WI  0.347028
42                                   WY  1.714678

In [8]:
mri_density.to_csv('/Users/apple/Desktop/healthcare/HW1/q4.csv')